"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AudioInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODEC_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_FIELD_NUMBER: builtins.int
    NUM_CHANNELS_FIELD_NUMBER: builtins.int
    codec: builtins.str
    """pcm16,pcm32,mp3,opus,etc."""
    sample_rate: builtins.int
    num_channels: builtins.int
    """number of input/output streams (e.g 2 for stereo speaker: left and right)"""
    def __init__(
        self,
        *,
        codec: builtins.str = ...,
        sample_rate: builtins.int = ...,
        num_channels: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["codec", b"codec", "num_channels", b"num_channels", "sample_rate", b"sample_rate"]) -> None: ...

global___AudioInfo = AudioInfo

@typing.final
class GetAudioRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DURATION_SECONDS_FIELD_NUMBER: builtins.int
    CODEC_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    MAX_DURATION_SECONDS_FIELD_NUMBER: builtins.int
    PREVIOUS_TIMESTAMP_FIELD_NUMBER: builtins.int
    name: builtins.str
    duration_seconds: builtins.int
    codec: builtins.str
    request_id: builtins.str
    max_duration_seconds: builtins.float
    previous_timestamp: builtins.float
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        duration_seconds: builtins.int = ...,
        codec: builtins.str = ...,
        request_id: builtins.str = ...,
        max_duration_seconds: builtins.float = ...,
        previous_timestamp: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["codec", b"codec", "duration_seconds", b"duration_seconds", "max_duration_seconds", b"max_duration_seconds", "name", b"name", "previous_timestamp", b"previous_timestamp", "request_id", b"request_id"]) -> None: ...

global___GetAudioRequest = GetAudioRequest

@typing.final
class AudioChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUDIO_DATA_FIELD_NUMBER: builtins.int
    INFO_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    START_TIMESTAMP_NANOSECONDS_FIELD_NUMBER: builtins.int
    END_TIMESTAMP_NANOSECONDS_FIELD_NUMBER: builtins.int
    audio_data: builtins.bytes
    sequence: builtins.int
    """Sequence number"""
    start_timestamp_nanoseconds: builtins.int
    end_timestamp_nanoseconds: builtins.int
    @property
    def info(self) -> global___AudioInfo: ...
    def __init__(
        self,
        *,
        audio_data: builtins.bytes = ...,
        info: global___AudioInfo | None = ...,
        sequence: builtins.int = ...,
        start_timestamp_nanoseconds: builtins.int = ...,
        end_timestamp_nanoseconds: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["info", b"info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["audio_data", b"audio_data", "end_timestamp_nanoseconds", b"end_timestamp_nanoseconds", "info", b"info", "sequence", b"sequence", "start_timestamp_nanoseconds", b"start_timestamp_nanoseconds"]) -> None: ...

global___AudioChunk = AudioChunk
