# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: audio.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.api.annotations_pb2
from . import audio_pb2


class AudioServiceBase(abc.ABC):

    @abc.abstractmethod
    async def GetAudio(self, stream: 'grpclib.server.Stream[audio_pb2.GetAudioRequest, audio_pb2.AudioChunk]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/AudioService/GetAudio': grpclib.const.Handler(
                self.GetAudio,
                grpclib.const.Cardinality.UNARY_STREAM,
                audio_pb2.GetAudioRequest,
                audio_pb2.AudioChunk,
            ),
        }


class AudioServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetAudio = grpclib.client.UnaryStreamMethod(
            channel,
            '/AudioService/GetAudio',
            audio_pb2.GetAudioRequest,
            audio_pb2.AudioChunk,
        )
