# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\x1a\x1cgoogle/api/annotations.proto\"e\n\tAudioInfo\x12\x14\n\x05\x63odec\x18\x01 \x01(\tR\x05\x63odec\x12\x1f\n\x0bsample_rate\x18\x02 \x01(\x05R\nsampleRate\x12!\n\x0cnum_channels\x18\x03 \x01(\x05R\x0bnumChannels\"\xe6\x01\n\x0fGetAudioRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12)\n\x10\x64uration_seconds\x18\x02 \x01(\x05R\x0f\x64urationSeconds\x12\x14\n\x05\x63odec\x18\x03 \x01(\tR\x05\x63odec\x12\x1d\n\nrequest_id\x18\x04 \x01(\tR\trequestId\x12\x30\n\x14max_duration_seconds\x18\x05 \x01(\x02R\x12maxDurationSeconds\x12-\n\x12previous_timestamp\x18\x06 \x01(\x02R\x11previousTimestamp\"\xe3\x01\n\nAudioChunk\x12\x1d\n\naudio_data\x18\x01 \x01(\x0cR\taudioData\x12\x1e\n\x04info\x18\x02 \x01(\x0b\x32\n.AudioInfoR\x04info\x12\x1a\n\x08sequence\x18\x03 \x01(\x05R\x08sequence\x12>\n\x1bstart_timestamp_nanoseconds\x18\x04 \x01(\x03R\x19startTimestampNanoseconds\x12:\n\x19\x65nd_timestamp_nanoseconds\x18\x05 \x01(\x03R\x17\x65ndTimestampNanoseconds2q\n\x0c\x41udioService\x12\x61\n\x08GetAudio\x12\x10.GetAudioRequest\x1a\x0b.AudioChunk\"4\x82\xd3\xe4\x93\x02.\",/olivia/api/v1/service/audio/{name}/GetAudio0\x01\x42\tZ\x07./audiob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./audio'
  _globals['_AUDIOSERVICE'].methods_by_name['GetAudio']._loaded_options = None
  _globals['_AUDIOSERVICE'].methods_by_name['GetAudio']._serialized_options = b'\202\323\344\223\002.\",/olivia/api/v1/service/audio/{name}/GetAudio'
  _globals['_AUDIOINFO']._serialized_start=45
  _globals['_AUDIOINFO']._serialized_end=146
  _globals['_GETAUDIOREQUEST']._serialized_start=149
  _globals['_GETAUDIOREQUEST']._serialized_end=379
  _globals['_AUDIOCHUNK']._serialized_start=382
  _globals['_AUDIOCHUNK']._serialized_end=609
  _globals['_AUDIOSERVICE']._serialized_start=611
  _globals['_AUDIOSERVICE']._serialized_end=724
# @@protoc_insertion_point(module_scope)
